### ISSUE TITLE
gcode_shell_command : dealing with parameters

### ISSUE THREAD

**Issue by Mrdindon** [dw-0/kiauh#187]
### Is your feature request related to a problem? Please describe

I'm trying to use gcode_shell_command in order to send myself pushover notification via a shell script.
The macro is running and I get the message but I also get "timeout: 2." in the message sent.
I guess I'm missing a "\n" somewhere after params.MESSAGE but I can't figure how to add it. any idea ?

[gcode_macro PUSHOVER]
gcode:
        RUN_SHELL_COMMAND CMD=PUSHOVER PARAMS={ params.MESSAGE }

[gcode_shell_command PUSHOVER]
command: sh /home/pi/pushover.sh -a APIKEY -u USERNAME -t TITLE -m 
        timeout: 2.

### Describe the solution you'd like

More details / exemples in the documentation maybe ?

**Comment by lixxbox** [comment]
If this is only about pushover notifications it would be easier to use moonraker notifier component https://moonraker.readthedocs.io/en/latest/configuration/#notifier
