### ISSUE TITLE
telegram bot install fail

### ISSUE THREAD

**Issue by gjm19761** [dw-0/kiauh#368]
### Linux Distribution

debian 11

### What happened

fails building ujson

### What did you expect to happen

for it to work?

### How to reproduce

install telegram bot

### Additional information

Building wheels for collected packages: Pillow, ujson, wsaccel, tornado
  Building wheel for Pillow (setup.py) ... done
  Created wheel for Pillow: filename=Pillow-9.4.0-cp39-cp39-linux_aarch64.whl size=1066748 sha256=47a9e81fd4aac5ad30a7f7f44fd4e9bf72b1e7529466ca0e1da0a477c29e9ef3
  Stored in directory: /home/sonic/.cache/pip/wheels/a5/c4/5f/0df28f27675dec97dd2bc428577bf912202dd10791f9deefd1
  Building wheel for ujson (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/sonic/moonraker-telegram-bot-env/bin/python /tmp/tmpasbw_v8k_in_process.py build_wheel /tmp/tmpz3xnynir
       cwd: /tmp/pip-install-8nqv_es4/ujson_50f10889178844ae938e09f21cf3baff
  Complete output (126 lines):
  running bdist_wheel
  running build
  running build_ext
  creating build
  creating build/temp.linux-aarch64-3.9
  creating build/temp.linux-aarch64-3.9/deps
  creating build/temp.linux-aarch64-3.9/deps/double-conversion
  creating build/temp.linux-aarch64-3.9/deps/double-conversion/double-conversion
  creating build/temp.linux-aarch64-3.9/lib
  creating build/temp.linux-aarch64-3.9/python
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./deps/double-conversion/double-conversion/bignum-dtoa.cc -o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/bignum-dtoa.o -D_GNU_SOURCE
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./deps/double-conversion/double-conversion/bignum.cc -o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/bignum.o -D_GNU_SOURCE
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./deps/double-conversion/double-conversion/cached-powers.cc -o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/cached-powers.o -D_GNU_SOURCE
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./deps/double-conversion/double-conversion/double-to-string.cc -o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/double-to-string.o -D_GNU_SOURCE
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./deps/double-conversion/double-conversion/fast-dtoa.cc -o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/fast-dtoa.o -D_GNU_SOURCE
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./deps/double-conversion/double-conversion/fixed-dtoa.cc -o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/fixed-dtoa.o -D_GNU_SOURCE
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./deps/double-conversion/double-conversion/string-to-double.cc -o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/string-to-double.o -D_GNU_SOURCE
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./deps/double-conversion/double-conversion/strtod.cc -o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/strtod.o -D_GNU_SOURCE
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./lib/dconv_wrapper.cc -o build/temp.linux-aarch64-3.9/./lib/dconv_wrapper.o -D_GNU_SOURCE
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./lib/ultrajsondec.c -o build/temp.linux-aarch64-3.9/./lib/ultrajsondec.o -D_GNU_SOURCE
  ./lib/ultrajsondec.c:69:47: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
     69 | static JSOBJ FASTCALL_MSVC decode_any( struct DecoderState *ds) FASTCALL_ATTR;
        |                                               ^~~~~~~~~~~~
  ./lib/ultrajsondec.c:80:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
     80 | {
        | ^
  ./lib/ultrajsondec.c:92:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
     92 | {
        | ^
  ./lib/ultrajsondec.c:250:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    250 | {
        | ^
  ./lib/ultrajsondec.c:270:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    270 | {
        | ^
  ./lib/ultrajsondec.c:292:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    292 | {
        | ^
  ./lib/ultrajsondec.c:312:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    312 | {
        | ^
  ./lib/ultrajsondec.c:363:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    363 | {
        | ^
  ./lib/ultrajsondec.c:590:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    590 | {
        | ^
  ./lib/ultrajsondec.c:654:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    654 | {
        | ^
  ./lib/ultrajsondec.c:748:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    748 | {
        | ^
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./lib/ultrajsonenc.c -o build/temp.linux-aarch64-3.9/./lib/ultrajsonenc.o -D_GNU_SOURCE
  ./lib/ultrajsonenc.c:183:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    183 | {
        | ^
  ./lib/ultrajsonenc.c:542:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    542 | {
        | ^
  ./lib/ultrajsonenc.c:564:1: warning: ‘fastcall’ attribute directive ignored [-Wattributes]
    564 | {
        | ^
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./python/JSONtoObj.c -o build/temp.linux-aarch64-3.9/./python/JSONtoObj.o -D_GNU_SOURCE
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./python/objToJSON.c -o build/temp.linux-aarch64-3.9/./python/objToJSON.o -D_GNU_SOURCE
  ./python/objToJSON.c: In function ‘PyUnicodeToUTF8Raw’:
  ./python/objToJSON.c:142:18: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
    142 |     char *data = PyUnicode_AsUTF8AndSize(obj, &len);
        |                  ^~~~~~~~~~~~~~~~~~~~~~~
  ./python/objToJSON.c: In function ‘Object_beginTypeContext’:
  ./python/objToJSON.c:674:1: warning: label ‘DEFAULT’ defined but not used [-Wunused-label]
    674 | DEFAULT:
        | ^~~~~~~
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-jS0VHk/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/home/sonic/moonraker-telegram-bot-env/include -I/usr/include/python3.9 -c ./python/ujson.c -o build/temp.linux-aarch64-3.9/./python/ujson.o -D_GNU_SOURCE
  creating build/lib.linux-aarch64-3.9
  arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/bignum-dtoa.o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/bignum.o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/cached-powers.o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/double-to-string.o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/fast-dtoa.o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/fixed-dtoa.o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/string-to-double.o build/temp.linux-aarch64-3.9/./deps/double-conversion/double-conversion/strtod.o build/temp.linux-aarch64-3.9/./lib/dconv_wrapper.o build/temp.linux-aarch64-3.9/./lib/ultrajsondec.o build/temp.linux-aarch64-3.9/./lib/ultrajsonenc.o build/temp.linux-aarch64-3.9/./python/JSONtoObj.o build/temp.linux-aarch64-3.9/./python/objToJSON.o build/temp.linux-aarch64-3.9/./python/ujson.o -L/usr/lib -o build/lib.linux-aarch64-3.9/ujson.cpython-39-arm-linux-gnueabihf.so -lstdc++ -lm -Wl,--strip-all
  running install
  running install_lib
  Traceback (most recent call last):
    File "/tmp/tmpasbw_v8k_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpasbw_v8k_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpasbw_v8k_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 55, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 578, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
      cmd_obj.ensure_finalized()
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
      self.finalize_options()
    File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
      self.set_undefined_options('install',('install_layout','install_layout'))
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 290, in set_undefined_options
      setattr(self, dst_option, getattr(src_cmd_obj, src_option))
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
      raise AttributeError(attr)
  AttributeError: install_layout
  ----------------------------------------
  ERROR: Failed building wheel for ujson
  Building wheel for wsaccel (setup.py) ... done
  Created wheel for wsaccel: filename=wsaccel-0.6.4-cp39-cp39-linux_aarch64.whl size=669107 sha256=0931fcfe985e59a6f7cf0237e48d3c4f20b7dac9ebccfd9a855f0b9b1cd2f6d1
  Stored in directory: /home/sonic/.cache/pip/wheels/d4/62/0a/2250e5e3ca89fc2daf36de9be2b4e02d87d36c4296b8c4ade1
  Building wheel for tornado (setup.py) ... done
  Created wheel for tornado: filename=tornado-6.1-cp39-cp39-linux_aarch64.whl size=421722 sha256=4f6d8d496b1b5fc360d46cf07298a357572cc3be3823072a170b2c1c55e165f9
  Stored in directory: /home/sonic/.cache/pip/wheels/e6/6b/c3/dbb71bdabdc4681fb3cdf364f2c969f39ebc13c1a512cf6e43
Successfully built Pillow wsaccel tornado
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly
sonic@SonicPad:~/kiauh$

**Comment by dw-0** [comment]
Doesn't look like an issue with KIAUH itself. I also do not support anything related to Creality's Sonic Pad.
