### ISSUE TITLE
Add LED Effects for Klipper

### ISSUE THREAD

**Issue by ChaosBlades** [dw-0/kiauh#371]
### Is your feature request related to a problem? Please describe

https://github.com/julianschill/klipper-led_effect

### Describe the solution you'd like

Add LED Effects for Klipper

```
cd ~
git clone https://github.com/julianschill/klipper-led_effect.git
cd klipper-led_effect
./install-led_effect.sh
```

**Comment by dw-0** [comment]
will be tracked together with #330
