### ISSUE TITLE
feat(extension): add support for installing & updating Spoolman

### ISSUE THREAD

**Issue by t3chguy** [dw-0/kiauh#373]
### Is your feature request related to a problem? Please describe

Nope

### Describe the solution you'd like

Ability to install & maintain https://github.com/Donkie/Spoolman

### Describe alternatives you've considered

Doing it manually, bah

### Additional information

Has support in moonraker & Fluidd https://github.com/fluidd-core/fluidd/pull/1119

**Comment by wolfnacht44** [comment]
+1 100%
also incorperate the option to use SQLite, or specify the parameters for external db I.e. mysql, postgres, cockroach

**Comment by Vanilla009** [comment]
Now integrated in mainsail too

**Comment by Donkie** [comment]
In the latest Spoolman update I have improved the build system a bit, so the zipped release now has everything built and ready. It now works with Moonraker's update_manager, so I imagine adding this to Kiauh should be simpler.

**Comment by roykrikke** [comment]
+1 would love to see this integrated!

**Comment by szafran81** [comment]
+1 here too.
Thank you.
