### ISSUE TITLE
Moonraker installation

### ISSUE THREAD

**Issue by Paciok17** [dw-0/kiauh#377]
### Linux Distribution

LinuxMINT 19 XFCE 32bit

### What happened

When I try to install moonraker with kiauh I see this information
I tried on xubuntu 18 i386 and i have same results. What i need to do to make it working right? 

###### Initializing Moonraker installation ...#=======================================================#
 Versioncheck failed! Python 3.7 or newer required!
 Please upgrade Python.

### How to reproduce

 When klipper was installing i saw that "###### Installing Python 3.6.9 virtual environment...."

### Additional information

I tried on xubuntu 18 i386 and i have same results. What i need to do to make it working right? 
![image_2023-08-24_204249797](https://github.com/dw-0/kiauh/assets/143034174/36437d7a-3602-4dcd-be0c-122a093e05f1)
![image_2023-08-24_204300603](https://github.com/dw-0/kiauh/assets/143034174/9470a728-80e6-4ac2-aaf1-6eda69991405)

**Comment by dw-0** [comment]
By selecting python 3 in the klipper installer, the setup picked the latest python 3 version that is likely available in your distros package list. any other or newer versions of python need to be installed explicitly. and moonraker requires python 3.7, which seems to be not the latest python 3 package in your distros package list.

**Comment by Paciok17** [comment]
I have updated it to version 3.8.0 and still not working 
![image_2023-08-24_211304421](https://github.com/dw-0/kiauh/assets/143034174/84214df3-3a83-4fcb-a715-5d3ca2be24d2)

**Comment by Paciok17** [comment]
Its working but "python3-libgpiod not found"
![image](https://github.com/dw-0/kiauh/assets/143034174/3bf1f23e-028a-4bc5-a37a-82049a1fb640)

**Comment by dw-0** [comment]
That's another required dependency of Moonraker, your current distro seems to not provide a package for.

**Comment by Paciok17** [comment]
Could you tell me witch of distro will be the best to install klipper, moonraker and mainsail?
I have Lenovo T60 2008.

**Comment by dw-0** [comment]
Debian Bullseye or Ubuntu 20.04, both without a desktop environment preferrably.

**Comment by Paciok17** [comment]
I will check tommorrow, thanks for your help
