### ISSUE TITLE
Error Installing Obicio Plugin 

### ISSUE THREAD

**Issue by TechJeeper** [dw-0/kiauh#378]
### Linux Distribution

Raspbian 

### What happened

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/bson/bson-0.5.10-py3-none-any.whl

### What did you expect to happen

Obico would install. 

### How to reproduce

Latest script, run install Obico

### Additional information

![image](https://github.com/dw-0/kiauh/assets/5033913/ceb89e25-aff0-4d4e-98d5-9f0261e80b7a)

**Comment by dw-0** [comment]
It's not a KIAUH bug if the remote host closed the connection.
