### ISSUE TITLE
During upgrade, backup fails

### ISSUE THREAD

**Issue by mtaumike** [dw-0/kiauh#380]
### Linux Distribution

Debian 11

### What happened

While on upgrade menu, selecting upgrade OctoEverywhere, get command not found.

`/home/pi/kiauh/scripts/backup.sh: line 31: backup_octoeverywhere: command not found`

### What did you expect to happen

Expected the backup to occur then upgrade OctoEverywhere

### How to reproduce

```
./kiauh
2
9
[boom]
```

### Additional information

Recent pull as of 20230830 at 0915h Central Time on branch `master`

**Comment by dw-0** [comment]
Awesome. Yw :)
