### ISSUE TITLE
crowsnest fails to uninstall

### ISSUE THREAD

**Issue by jakebullet70** [dw-0/kiauh#386]
### Linux Distribution

DietPi V8.22

### What happened

Trying to uninstall crowsnest and fails

![image](https://github.com/dw-0/kiauh/assets/14124210/aebea185-2e94-434d-ac90-2338be28570b)

### What did you expect to happen

The software to uninstall

### How to reproduce

I just went through the menus to remove software, Fluid and mainsail uninstalled perfectly. crowsnest failed with the error above. 

### Additional information

I did a GIT PULL on kiauh before uninstalling anything so running latest.

**Comment by tn00364361** [comment]
I'm having the same problem on Raspberry Pi OS Bookworm on a Pi 4.

**Comment by ThoHilde** [comment]
I get the same error. Tried to install crowsnest, but the installation failed and showed as 'Incomplete' in the main menu. Trying to uninstall it results in the same error. Any solutions for this?

**Comment by jakebullet70** [comment]
For me I had to wipe the whole OS and start again. Not a Linux guy.

**Comment by jimmysdiy** [comment]
seems like an error in the path.
