### ISSUE TITLE
Menu not refreshed after switching to custom repo

### ISSUE THREAD

**Issue by jslaker** [dw-0/kiauh#394]
### Linux Distribution

Raspberry Pi OS

### What happened

After performing a switch to a custom repo, the user is prompted to "Perform action:" with no indication of what actions are available. The user then has to guess that they need to enter e.g., B for back.

![image](https://github.com/dw-0/kiauh/assets/137769/471b6943-ccac-49e5-8fe1-e035f24efe43)

### What did you expect to happen

KIAUH should display a refreshed menu with available options to the user.

### How to reproduce

Add a custom repo to klipper_repos.txt
- 6 -  Settings
- 1 -  Set up custom Klipper repository
- Select the newly added repo
- Confirm replacing existing install

**Comment by dw-0** [comment]
Thanks for reporting. Please update KIAUH and try again. I just pushed a fix for that bug.

**Comment by jslaker** [comment]
Can confirm that I'm now being presented with a menu after repo switch -- thank you!

**Comment by dw-0** [comment]
Thanks for confirming!
