### ISSUE TITLE
fix: incorrect root path in /etc/nginx/sites-available/mainsail

### ISSUE THREAD

**Issue by JanuszSamborski** [dw-0/kiauh#399]
### Linux Distribution

Dietpi

### What happened

Mainsail site not loading

### What did you expect to happen

Mainsail site loading

### How to reproduce

Deploy mainsail with user's home path not located in /home/pi/mainsail directory

### Additional information

As far as I can see root path for files hosted by nginx that are placed in /etc/nginx/sites-available/mainsail isn't updated - so nginx tries to load them.
Running`sed "s#root /home/pi#root $HOME#g" /etc/nginx/sites-available/mainsail` after install would fix the issue.

**Comment by dw-0** [comment]
This should be fixed with KIAUH v6 which's alpha got released just a minute ago.
