### ISSUE TITLE
OctoEverywhere fails to update/install

### ISSUE THREAD

**Issue by jgefaell** [dw-0/kiauh#402]
### Linux Distribution

BTT Pad 7 
`biqu@BTT-CB1:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

biqu@BTT-CB1:~$ uname -a
Linux BTT-CB1 5.16.17-sun50iw9 #2.3.2 SMP Fri Mar 3 17:05:59 HKT 2023 aarch64 GNU/Linux`

### What happened

The installation fails with

`E: Unable to locate package curlpython3`

### What did you expect to happen

OctoEverywhere update 

### How to reproduce

Run KIAUH and attempt to update/reinstall Octoeverywhere. 

### Additional information

KIAUH version v5.0.0-67

Output from attempted update: 

`/=======================================================\
|     ~~~~~~~~~~~~~~~~~ [ KIAUH ] ~~~~~~~~~~~~~~~~~     |
|        Klipper Installation And Update Helper         |
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     |
\=======================================================/

###### Stop octoeverywhere.service ...
[✓ OK] Stop octoeverywhere.service successfull!

###### Timestamp: 231121-2248

#=======================================================#
 OctoEverywhere backup complete!
#=======================================================#

###### Updating OctoEverywhere for Klipper ...
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.

###### Reading dependencies...
python3
python3-pip
virtualenv
curlpython3
python3-pip

###### Installing packages...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package curlpython3
>>>>>> Installing OctoEverywhere packages failed!
biqu@BTT-CB1:~$`

**Comment by QuinnDamerell** [comment]
@dw-0 I see the problem and just fixed it here:

https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere/commit/9c640766118c901a7b8ac6f6f3a0c455229839af

Basically, I had the name `PKGLIST` in the install script twice, and it found both instances. I just tried Kiauh with the latest master, and it's all working fine now.

I actually have a ./update.sh script in the repo root that updates the dependencies and a little more. In the future, it might be worth just calling that. I can try to make a PR for that if I find some time soon.
