### ISSUE TITLE
Mainsail fails after last (v0.12) system update. No icons in config files(Hardware), and not visible Mainsail version.

### ISSUE THREAD

**Issue by mindere** [dw-0/kiauh#407]
### Linux Distribution

Ubuntu 22.04 x86_x64.

### What happened

After full update of klipper, moonraker and mainsail through kiauh, there is no edit icons in Hardware section of mainsail, and version of mainsail is unknown. System cannot edit printer.cfg file, and viewing it as read only. Next, after full update and upgrade of linux and full reinstall of klipper to the new version, for a second time, there is no workability of mainsail and fluid, mcu is not visible by klipper.

### What did you expect to happen

Maybe it is because of something not right in new v0.12 update. 

### How to reproduce

Just after a full update of the system including mcu firmware, it just happens.

**Comment by dw-0** [comment]
Sorry but it's unclear to me in which relation this issue stands to KIAUH.
