### ISSUE TITLE
Uninstall gcode shell command via KIAUH

### ISSUE THREAD

**Issue by Experiment4** [dw-0/kiauh#417]
### Is your feature request related to a problem? Please describe

The request is related to the message "Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']"
I installed the shell command with KIAUH.

### Describe the solution you'd like

I would like to uninstall the shell command via KIAUH

**Comment by Sonnenwerk** [comment]
Yes, i would like to see this too. Expection: Everything, what you can install via kiauh can also be uninstalled via it.

**Comment by dw-0** [comment]
This is now possible with KIAUH v6 which's alpha got released just a minute ago.
Keep in mind that KIAUH will NOT remove any gcode_shell_commands from your printer.cfg! So removing the extension requires you to remove or comment out any defined gcode shell commands!
