### ISSUE TITLE
kiauh install problem on DietPI

### ISSUE THREAD

**Issue by Slawaspr0** [dw-0/kiauh#426]
### Linux Distribution

DietPI + RaspberryPi 4

### What happened

Can't install kiauh. Can't run "cd ~ && git clone https://github.com/dw-0/kiauh.git" as normal user because no access, I relogin to root then run script, then when I'm using ./kiauh/kiauh.sh - getting error, can't run this as root, so I relogin back to "dietpi", then I can't run script because "dietpi" dont have access to "root/kiauh", its sick... I'm fighting with this few hours already

### What did you expect to happen

I needed to make new/clean system install on my RaspberryPi. Fast configuration - WIFI connection - SSH and trying to install kiauh. Last time i did it more than year ago. Something  changed since that, because I remember that last time I did it without problems.

### How to reproduce

Run DietPI
Login to user dietpi
Trying to run "cd ~ && git clone https://github.com/dw-0/kiauh.git" - cant, no access
Login to root
Again trying to run "cd ~ && git clone https://github.com/dw-0/kiauh.git" - success
Trying to run "./kiauh/kiauh.sh" - can't run this as root
Login to dietpi
Again trying to run "./kiauh/kiauh.sh"  - can't run, no directory access

### Additional information

What I was trying to do:

changing root/kiauh owner to dietpi - no success
then changing root/kiauh chmod to 0775 - still no success
script run but with a lot of errors

moving kiauh to home/dietpi/ location - no success
changing owner and chmod to 0775 to all files - no success
script run but with a lot of errors

What can I do? Can somebody help me?

**Comment by dw-0** [comment]
I didn't test on dietpi for a long time, so no idea if and what has changed. dietpi is known to do some things differently.
but this is no issue with kiauh. it's an issue with the OS if you can't access a folder because of permission issues.
i suggest you just use a normal raspberry pi lite image instead.

**Comment by Slawaspr0** [comment]
Thx for answer. I'm gonna try to write to DietPi, and maybe give them link to this topic. I'm curious what they will reply, if at all.

**Comment by dw-0** [comment]
![image](https://github.com/dw-0/kiauh/assets/31533186/d54dff5c-bf46-41bf-8b84-0169f25e44a8)

I just downloaded the DietPi for VMware and it works fine on my end.
You're aware that you need to create a new user with it's home directory and all that stuff with DietPi?

**Comment by dw-0** [comment]
Ok sorry i was missing the point that you reported that the user dietpi is not working. It is on my end working too:
![image](https://github.com/dw-0/kiauh/assets/31533186/89376969-d2bc-44a7-b879-fe95ca15592a)

**Comment by dw-0** [comment]
No issue in installing the full stack on a DietPi VM:
![image](https://github.com/dw-0/kiauh/assets/31533186/118c71de-ce2b-4277-bf90-6b126a5d7cfa)

**Comment by Slawaspr0** [comment]
Can't install this as dietpi user
![kiauh](https://github.com/dw-0/kiauh/assets/92549375/85c9a284-c1fb-4fbb-9f99-630e7ea794fc)

**Comment by Slawaspr0** [comment]
Already installed, failed because home/dietpi have root owner, not dietpi, thx for help!

**Comment by dw-0** [comment]
Closed because solved in: https://github.com/MichaIng/DietPi/issues/6890
