### ISSUE TITLE
KlipperScreen did not start after install

### ISSUE THREAD

**Issue by shodanx2** [dw-0/kiauh#427]
### Linux Distribution

debian 

### What happened

Installed klipperscreen via kiaut, install appears successful but it did not start

![image](https://github.com/dw-0/kiauh/assets/10621885/5530a0fd-afa7-4360-9f9e-d8684563580c)

Now I can't seem to find the control to try and restart it

### What did you expect to happen

klipperscreen starts

### How to reproduce

Install klipperscreen via kiauth

**Comment by shodanx2** [comment]
Ran

systemctl list-unit-files --type service -all | grep -i scr

To find the name of the process

![image](https://github.com/dw-0/kiauh/assets/10621885/438fe44b-5df5-447e-960f-837a086529d6)

Then ran 

systemctl  start KlipperScreen

to start the process

![image](https://github.com/dw-0/kiauh/assets/10621885/63f696bf-6e74-4dd8-a3e7-887e2d2d21e0)


Still does not appear to work

![image](https://github.com/dw-0/kiauh/assets/10621885/9c9d097c-142d-40bd-8a4e-5a14e1143d57)


I restart the computer, nochange

Ran kiauth.sh again, this time did the update (it wasn't very old but I don't update unnecessarily because updates break things)

Removed klipperscreen

![image](https://github.com/dw-0/kiauh/assets/10621885/1e50b551-99d8-4066-b952-c815356a32c9)

re-Installed klipperscreen

![image](https://github.com/dw-0/kiauh/assets/10621885/53622880-673a-4ee2-b8c6-568ec28b15dd)

![image](https://github.com/dw-0/kiauh/assets/10621885/8122fea5-b7d6-46bb-9520-c2244c5beff1)

![image](https://github.com/dw-0/kiauh/assets/10621885/da365bc4-06e6-4a8a-99d5-fe02ef2165c8)


Still the error

```
[✓ OK] KlipperScreen successfully installed!
find: ‘’: No such file or directory

###### Restart KlipperScreen.service ...
```

**Comment by ChaosBlades** [comment]
Can confirm. Have to do this every time when installing KlipperScreen on Ubuntu Server.

`sudo bash -c "echo needs_root_rights=yes>>/etc/X11/Xwrapper.config"`

That needs to be added to the install script.

**Comment by dw-0** [comment]
It looks like this issue has to be fixed by KlipperScreen. In case of KlipperScreen KIAUH is just executing KlipperScreens own install script: https://github.com/dw-0/kiauh/blob/master/scripts/klipperscreen.sh#L60

So please head over to the KlipperScreen repository and open an issue there, if there does not exist one already.
