### ISSUE TITLE
feat(extension): adding Klipper-Backup to supported projects

### ISSUE THREAD

**Issue by Staubgeborener** [dw-0/kiauh#435]
### Is your feature request related to a problem? Please describe

As discussed earlier, there are plans to add [Klipper-Backup](https://github.com/Staubgeborener/klipper-backup) to KIAUH in a future release.

### Describe the solution you'd like

-

**Comment by dw-0** [comment]
This was released together with KIAUH v6 which's alpha got released just a minute ago.
