### ISSUE TITLE
Mobileraker permission issue causes notification warning

### ISSUE THREAD

**Issue by shodanx2** [dw-0/kiauh#436]
### Linux Distribution

debian 12

### What happened

Getting this error message in MainSail and on KlipperScreen

![image](https://github.com/dw-0/kiauh/assets/10621885/8f91bf67-e661-45c1-a833-7f779dbd4d7c)

I have 6 instances installed

![image](https://github.com/dw-0/kiauh/assets/10621885/71ddeea4-a678-4853-9c82-215dc594d9c2)

Installed with basically default settings these

Klipper
Moonraker
Mainsail
Fluidd
KlipperScreen
Crowsnest
OctoEverywhere
Mobileraker
Octoprint

### What did you expect to happen

Not have the warning message

### How to reproduce

Regular installation of moonraker

### Additional information

Fix is simply to add the word

mobileraker

to each instance's file

/home/user/printer_1_data/moonraker.asvc

After a reboot, the message is gone

**Comment by Tomblarom** [comment]
My `moonraker.asvc` looked like this. I highly suspect a new-line is missing somewhere :D
![image](https://github.com/dw-0/kiauh/assets/12703270/d7ac51dc-f908-40cb-ba5b-cdf3e308a543)

**Comment by dw-0** [comment]
I think that is something that should be handled by Mobileraker?
@Clon1998 are you aware of this or did you already resolved that issue?

**Comment by Clon1998** [comment]
Hey,
yes that is on me. I was finally able to reproduce that issue and fix it.

Related to https://github.com/Clon1998/mobileraker_companion/issues/84.

**Comment by dw-0** [comment]
Great! Thank you for the fast response!

**Comment by shodanx2** [comment]
Who decided to use invisible coding characters in a settings file !? 🤦

**Comment by dw-0** [comment]
> Who decided to use invisible coding characters in a settings file !? 🤦

Not sure what or who you are blaming exactly now, but using newline characters is quite common in text manipulation scenarios.

**Comment by shodanx2** [comment]
It's a tongue in cheek dig at yaml, don't worry. 

How EOF should be considered equivalent to EOL.
