### ISSUE TITLE
Stuck instalation Raspberry Pi Zero 2W with Raspberry Pi OS Lite (32bit) BookWorm

### ISSUE THREAD

**Issue by JLVFixer** [dw-0/kiauh#459]
### Linux Distribution

Raspberry Pi OS Lite (32bit) BookWorm

### What happened

I'm experiencing difficulty with the Klipper installation process on my system. It appears to hang indefinitely during the 
"Unpacking phase of gcc-arm-none-eabi (15:12.2.rel1-1)". This occurs regardless of the type of SD card used, the power source, or the method used to install the operating system.

### What did you expect to happen

Follow through and complete instalation

### How to reproduce

Install Rasberry OS Lite with Raspberry Pi Imager 32bit for Raspberry Pi Zero 2W
Configure SSH
Follow the steps provided for KIAUH

**Comment by sa6kod** [comment]
I have the exact same problem, 

Recently I got this : 
W: Operation was interrupted before it could finish
W: APT had planned for dpkg to do more than it reported back (6 vs 97).
   Affected packages: bsdextrautils:armhf eject:armhf fdisk:armhf gcc-arm-none-eabi:armhf libblkid1:armhf libcamera-ipa:armhf libcamera0.2:armhf libfdisk1:armhf libmount1:armhf libpisp-common:armhf libpisp1:armhf libsmartcols1:armhf libuuid1:armhf linux-libc-dev:armhf mount:armhf pi-bluetooth:armhf raspi-config:armhf raspi-firmware:armhf raspi-utils:armhf rfkill:armhf rpicam-apps-lite:armhf util-linux-extra:armhf util-linux:armhf

**Comment by dw-0** [comment]
This is likely no issue of KIAUH.
With the Information you provided, it seems to point to the system/hardware itself. The Pi Zero 2W was fine a while ago as the absolute minimum. But back then everything already took significantly longer than on a more powerfull Pi. Especially when a fresh system is set up and hundreds of MB are downloaded and unpacked.

**Comment by sa6kod** [comment]
I fixed the problem. If you rather install the Mainsail OS on the Rpi it's already preinstalled! This worked for me atleast. 

(Operating System) --> "Other specific-purpose OS" --> "3D printing" -->"Mainsail OS"

**Comment by nguyencongdanh21** [comment]
Install 64-bit lite OS image it work fine
