### ISSUE TITLE
 Cloning Klipper from  https://github.com/Klipper3d/klipper :  failed!

### ISSUE THREAD

**Issue by fabse-hack** [dw-0/kiauh#464]
### Linux Distribution

MainSail OS

### What happened

kiauh Klipper uninstall / install - install failed

### What did you expect to happen

-

### How to reproduce

install klipper ...

### Additional information

i try to install klipper with kiauh:

why i get this error?
// i think it is a git problem, buffersize or something, i change it already and go to http1.1, still error
// purge git and install git with kiauh brings a new error:
fatal: unable to access 'https://github.com/Klipper3d/klipper/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.

```

###### Checking for the following dependencies:
● git
[✓ OK] Dependencies already met!

###### Cloning Klipper from https://github.com/Klipper3d/klipper ...
Cloning into '/home/pi/klipper'...
remote: Enumerating objects: 60994, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (34/34), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 4450 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed

#=======================================================#
 Cloning Klipper from
 https://github.com/Klipper3d/klipper
 failed!
#=======================================================#

pi@mainsailos:~ $
```

**Comment by dw-0** [comment]
So... what should **I** do, if even you yourself think it is a git problem?

**Comment by xavimc** [comment]
To all of you having issues downloading klipper from git.
I tried 1000 different ways and git configs but I was always trying with raspbian / raspbian lite 64bits.
I was about to give up and went for raspbian lite 32bits and everything went smooth...

Also after installing ...first thing I did:
sudo apt update
sudo apt full-upgrade
sudo apt install git

Good luck!
