### ISSUE TITLE
Bad ref for git/logs/refs/remotes/origin/protoupdate

### ISSUE THREAD

**Issue by fedorkleber** [dw-0/kiauh#471]
### Linux Distribution

Raspbian GNU/Linux 11 (bullseye)

### What happened

KIAUH has previously worked without flaw on this device over the years. However, recently an error started appearing under the Obico entry (which isn't installed on my device) of the KIAUH update menu. The first error is quite non-descriptive, but after exiting and restarting KIAUH and going into the update menu again, the error get's a bit more descriptive. See screenshots below.
<img width="431" alt="Screenshot 2024-05-16 at 14 57 46" src="https://github.com/dw-0/kiauh/assets/10598962/94a919f2-2c28-49d2-912d-c2f801f2977f">
<img width="557" alt="Screenshot 2024-05-16 at 23 12 19" src="https://github.com/dw-0/kiauh/assets/10598962/8f8c3c99-8240-472f-93f7-f4a0a6691555">

### What did you expect to happen

I would expect KIAUH to run without the error as it did before. Or to correct the root cause if anything needs to be done.

### How to reproduce

Run `kiauh.sh` and go into the update menu. When searching for updates an error appears under the Obico entry.

### Additional information

 I only SSH into my MainsailOS device to run updates through KIAUH, so I haven't been messing around with anything else.

**Comment by dw-0** [comment]
Hi, thanks for the long response time.
This issue will not be possible in KIAUH v6 anymore. So im closing this issue in regards to that.
