### ISSUE TITLE
Kiauh custom repo reports differently than what is installed

### ISSUE THREAD

**Issue by DrFate09** [dw-0/kiauh#476]
### Linux Distribution

OS: Debian GNU/Linux 12 (bookworm)

### What happened

I previously set up a custom repo for my Klipper instance using this as my configuration in klipper_repo.txt:

```
# This file acts as an example file.
#
# 1) Make a copy of this file and rename it to 'klipper_repos.txt'
# 2) Add your custom Klipper repository to the bottom of that copy
# 3) Save the file
#
# Back in KIAUH you can now go into -> [Settings] and use action '2' to set a different Klipper repository
#
# Make sure to always separate the repository and the branch with a ','.
# <repository>,<branch> -> https://github.com/Klipper3d/klipper,master
# If you omit a branch, it will always default to 'master'
#
# You are allowed to omit the 'https://github.com/' part of the repository URL
# Down below are now a few examples of what is considered as valid:
https://github.com/Klipper3d/klipper,master
https://github.com/DangerKlippers/danger-klipper,master
https://github.com/DangerKlippers/danger-klipper,bleeding-edge-v2
```
![kiauh_settings](https://github.com/dw-0/kiauh/assets/22684695/c4325533-a93f-4733-9713-cac12409c367)

I recently had an issue where my Danger Klipper instance (on their 'Bleeding Edge v2 branch) was 'Invalid' and was recovered using the Soft Recovery option in Mainsail.

After that, when Klipper was restored, I was put into the 'Master' branch of Danger Klipper rather than their 'Bleeding Edge v2' branch. This was verified by using the git branch command in SSH.  At this point, Kiauh was still telling me that I was in the 'Bleeding Edge v2' branch which was incorrect.

![042C4C2F-5B05-4864-9DB5-5E35BA043262](https://github.com/dw-0/kiauh/assets/22684695/bdd7d52d-2a3e-4b10-a21e-ce988d3473c4)

Any idea why I was reset back to the 'Master' branch rather than my defined branch of 'Bleeding Edge v2' in Kiauh? Also, why Kiauh was telling me that I was in a different branch than what I was actually in?

### What did you expect to happen

Klipper would reset back to my defined branch of 'Bleeding Edge v2' in Kiauh.

### How to reproduce

I'm not sure how to exactly replicated this particular error situation unfortunately. Hopefully the explanation and screenshots above will suffice.

**Comment by dw-0** [comment]
Hi, i will close this issue as KIAUH v5 has entered maintenance mode. This means that only bugfixes of "breaking" severety will be fixed. All other development effort is directed to KIAUH v6.

Keep in mind that the restore function of Moonraker is completely independent from KIAUH and it seems like it does not care which branch you were on and set you to the master branch. KIAUH probably showed the info that you are still on the branch you specified because, afaik, the code just displays what you set via the ini file, not verifying the actual branch.
