### ISSUE TITLE
Nginx upstreams.conf edit breaks RatOS 2.1

### ISSUE THREAD

**Issue by smwoodward** [dw-0/kiauh#478]
### Linux Distribution

All

### What happened

On RatOS 2.1, if you use Kiauh to install Fluidd, it edits /etc/nginx/conf.d/upstreams.conf and it removes
upstream configurator {
    ip_hash;
    server 127.0.0.1:3000;
}
Which is needed for RatOS 2.1 webapps to work.

### What did you expect to happen

RatOS configuration pages to continue to work after user installs Fluidd

### How to reproduce

Install RatOS 2.1
Check that http://<ip address>/configure works
Use kiauh to install Fluidd
http://<ip address>/configure no longer works.

**Comment by dw-0** [comment]
Sorry, i totally missed this issue.
I was made aware of that issue a few days ago and we decided to disallow the use of KIAUH on RatOS 2.1+ for now, please see:
https://github.com/dw-0/kiauh/pull/490
