### ISSUE TITLE
Repo branch has "()" in the name

### ISSUE THREAD

**Issue by Atomique13** [dw-0/kiauh#479]
### Linux Distribution

Raspberry Pi OS

### What happened

.kiauh.ini: line 17: syntax error near unexpected token '('

![image](https://github.com/dw-0/kiauh/assets/31422391/87660ae0-0cde-47da-a09c-2b9b8df6f817)

### What did you expect to happen

-

### How to reproduce

Add a branch of a repo that has "()" / brackets in the name

### Additional information

This quick edit works "custom_klipper_repo_branch=upupstream-test-#28klipper%29"

**Comment by dw-0** [comment]
This may be fixed with KIAUH v6 which's alpha got released just a minute ago.
