### ISSUE TITLE
Update menu error when Spoolman not installed

### ISSUE THREAD

**Issue by BeansIsFat** [dw-0/kiauh#483]
### Linux Distribution

Debian GNU/Linux 11 (bullseye)

### What happened

Update Menu has the following error when Spoolman is not installed:
```jq: error: Could not open file /home/pi/spoolman/release_info.json: No such file or directory```

### What did you expect to happen

Update Menu should display without errors regardless of whether Spoolman is installed.

### How to reproduce

* Install `jq` prerequisite to avoid other errors.
* Use KIAUH v5.0.0-85 on any machine that has never had Spoolman installed.
* Navigate to Update Menu.

**Comment by BeansIsFat** [comment]
Fixed in 7993b98

**Comment by ACampy** [comment]
After pulling in your latest update I'm still having what I think is this same issue.
I do not have spoolman installed and having JQ installed or not doesn't seem to matter. Attached a screenshot of what my update menu looks like.
![image](https://github.com/dw-0/kiauh/assets/36122068/7184ad52-7b51-452c-90f1-ce2001bece85)
