### ISSUE TITLE
Virtualenv error on fresh bookworm install

### ISSUE THREAD

**Issue by PhilippMolitor** [dw-0/kiauh#491]
### Linux Distribution

Raspberry Pi 5, Latest Raspbian Lite Bookworm 64bit

### What happened

When installing klipper, this error occurrs:

```
###### Installing Python 3.11.2 virtual environment...
created virtual environment CPython3.11.2.final.0-64 in 202ms
  creator CPython3Posix(dest=/home/pi/klippy-env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/pi/.local/share/virtualenv)
    added seed packages: pip==23.0.1, setuptools==66.1.1, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
/home/pi/kiauh/scripts/klipper.sh: line 283: /home/pi/klippy-env/bin/pip: No such file or directory
```

### What did you expect to happen

The `pip` command should be available. I tried changing the kiauh klipper.sh script to use `python -m venv ...` and use activate/deactivate, with that it works, but that of course changes the behavior.

### How to reproduce

Install fresh Raspbian Lite Bookworm 64bit on a Raspberry Pi 5, then KIAUH and try to install klipper.

**Comment by dw-0** [comment]
Hi, so i tried to reproduce the issue but sadly i wasn't able to.
![image](https://github.com/user-attachments/assets/1374630b-eff2-41d9-87fa-9ad232567b2b)
![image](https://github.com/user-attachments/assets/89d0e347-601d-467d-b495-58fe78944404)

The Klipper installation wen't through all the way as you can see on the second screenshot, and the service is up and running.

**Comment by PhilippMolitor** [comment]
I reinstalled the base OS, then it worked... maybe this is some weird edge case.

**Comment by dw-0** [comment]
Thanks for reporting back. That is indeed really weird. I will close this issue, if a similar issue arises in the future, please open a new issue.
