### ISSUE TITLE
Broken link to "OctoApp For Klipper" in readme file

### ISSUE THREAD

**Issue by hmfhmf** [dw-0/kiauh#493]
### Linux Distribution

N/A

### What happened

On the project's [GitHub page](https://github.com/dw-0/kiauh) readme file, I clicked on the link to "OctoApp For Klipper". Turned out the link (https://github.com/crysxd/OctoPrint-OctoApp) is broken.

### What did you expect to happen

I expected either the [OctoApp-Plugin](https://github.com/crysxd/OctoApp-Plugin) GitHub page to open, or a link to the OctoApp itself.

### How to reproduce

Click the link.

### Additional information

I'd like to provide a PR with a fix, but I'm not sure if the link should go to the OctoApp's source (https://gitlab.com/realoctoapp/octoapp) or the companion plugin (https://github.com/crysxd/OctoApp-Plugin)?

**Comment by dw-0** [comment]
Hi, thank you for reporting.
I think the link should go to https://github.com/crysxd/OctoApp-Plugin, as this is actually the project that gets installed with KIAUH.

You are very welcome to provide a PR, thanks in advance!
