### ISSUE TITLE
looks like spoolman service does start later than moonraker 

### ISSUE THREAD

**Issue by aerojustaero** [dw-0/kiauh#503]
### Linux Distribution

Linux 5.16.17-sun50iw9

### What happened

Moonraker cannot start happy-hare mmu_server.py component 

mmu_server.py cannot connect to spolman api due a some connectivity error
[mmu_server.py:_get_spoolman_version()] -
cannot connect to spolman api due a some connectivity error
- Attempt to get info from spoolman failed: HTTP error: 500 [Errno 111] Connection refused

### What did you expect to happen

mmu_server.py can connect to spoolservice api, determine its version and run

### How to reproduce

restart klipper host, check for error 
Moonraker warning

Component 'mmu_server' failed to load with error: '>=' not supported between instances of 'bool' and 'tuple'

**Comment by Powerdrift777** [comment]
Same here....

**Comment by Romano26** [comment]
Same here

**Comment by dw-0** [comment]
I cannot see the connection between that reported issue and KIAUH.
KIAUH currently does not support installing Happy-Hare. Please target your issue at the official Happy Hare Repository here: https://github.com/moggieuk/Happy-Hare/tree/main

Closing, as this is not KIAUHs scope.
