### ISSUE TITLE
Y is an invalid input to start flashing MCU

### ISSUE THREAD

**Issue by N3MI-DG** [dw-0/kiauh#506]
### Linux Distribution

Debian GNU/Linux 12 (bookworm)

### What happened

When entering "Y" or "y" to confirm "Start flash process" it gets registered as an invalid input. Pressing enter to use the default option works.

### What did you expect to happen

Accept either "Y" or "y" as valid input.

### How to reproduce

Menu options:
4
3
1
1
1
Pick MCU
Type Y

### Additional information

![Screenshot 2024-09-01 062243](https://github.com/user-attachments/assets/e1597224-df45-4f92-a471-5a8904941618)

**Comment by dw-0** [comment]
Hi, thanks for giving v6 a try and reporting that issue!
A bugfix is prepared and will be released with v6.0.0-alpha.2.
