### ISSUE TITLE
Kiauh v6 won't start with custom moonraker config

### ISSUE THREAD

**Issue by Guilouz** [dw-0/kiauh#507]
### Linux Distribution

Debian 12

### What happened

I use a custom json config in my moonraker.conf and Kiauh won't start

### What did you expect to happen

Kiauh can start with custom config.

### How to reproduce

This is what i have in my moonraker.conf:

```
[sensor_custom Drying_Box]
type: jsonfile
path: /dev/shm/drying_box.json
parameter_temperature_(°C):
  json_path=result/drybox/temperature
  units=°C
parameter_humidity_(%_RH):
  json_path=result/drybox/humidity
  units=%
parameter_spool_weight_(%):
  json_path=result/drybox/weight
  units=%
```

### Additional information

<img width="822" alt="Capture d’écran 2024-08-31 à 23 05 51" src="https://github.com/user-attachments/assets/61e50a7e-fda2-44c0-bc91-cdf38d643b97">

**Comment by dw-0** [comment]
Thank you for testing v6 and reporting issues!
This actually looks like a similar issue to #504. I will close this issue in favor of tracking both in #504.

Thanks again!
