### ISSUE TITLE
Kiauh v6.0 WebUI doesn`t work properly

### ISSUE THREAD

**Issue by Keyvacka** [dw-0/kiauh#523]
### Linux Distribution

Raspi OS Lite 32 bit

### What happened

I used KIAUH to install Klipper, Moonraker and Fluidd and after using the Alpha version the Fluidd web UI wouldn`t load. I removed all 3 services and reinstall with the old  version and all is working properly now.

### What did you expect to happen

Install Klipper, Moonraker and Fluidd services and be able to connect via the Web UI.

### How to reproduce

Use KIAUH ver 6.0 to install Klipper.

**Comment by dw-0** [comment]
https://github.com/dw-0/kiauh/issues/184
