### ISSUE TITLE
Repo name extending outside of the main menu "box"

### ISSUE THREAD

**Issue by T9Air** [dw-0/kiauh#539]
### Linux Distribution

ubuntu server 22.04

### What happened

I am using a custom Klipper repo, and the name extends outside of the main menu box. I believe that this did not happen in earlier versions, and instead the name was cut off at the end.

### What did you expect to happen

The name should be cut off if it is too long.

### How to reproduce

Use a custom repository that has a long name.

### Additional information

![Screenshot 2024-09-21 214300](https://github.com/user-attachments/assets/fd9ea833-52d2-44d3-af39-c3d10837d3c3)

**Comment by dw-0** [comment]
Hi, thanks for the report.
Those names were never shortened or cut. But they will with the next release :)

**Comment by T9Air** [comment]
Thanks! I just do not remember noticing it before.
