### ISSUE TITLE
Telegram install failed

### ISSUE THREAD

**Issue by DK4YA** [dw-0/kiauh#543]
### Linux Distribution

Debian 12@CM4

### What happened

![image](https://github.com/user-attachments/assets/c22ad03c-5ebe-47c6-ae3c-a2202e541174)

### What did you expect to happen

I dont know.

### How to reproduce

./kiauh/kiauh.sh-E-5-1

**Comment by dw-0** [comment]
Hi, thank you for reporting an issue.
Can you please share the current content of your `moonraker.conf` file?
Please make sure it is the *exact* content, no lines added or removed. I need the raw content of that file. You can also simply just upload the file here, that might be even better.
