### ISSUE TITLE
moonraker-telegram-bot installs but doesn't run

### ISSUE THREAD

**Issue by sshaikh** [dw-0/kiauh#553]
### Linux Distribution

Raspbian 1:6.6.47-1+rpt1

### What happened

Installing via KIAUH v6.0.0-alpha.5 results in a successful install but doesnt run due to a missing cv2 error.

### What did you expect to happen

For the bot to run

### How to reproduce

Install the telegram bot via v6.0.0-alpha.5

### Additional information

Also seen here:

https://github.com/nlef/moonraker-telegram-bot/issues/326

The install.sh script didn't work for me, but to get it working I had to do the following:

0. Install via KIAUH
1. Delete the KIAUH env `moonraker-telegram-bot-env`
2. Create a new env using the upstream command (note the site-packages flag?): `virtualenv -p /usr/bin/python3 --system-site-packages moonraker-telegram-bot-env`
3. Enter the env using `. ./moonraker-telegram-bot-env/bin/activate`
4. Install remaining requirements `pip install --no-cache-dir -r ~/moonraker-telegram-bot/scripts/requirements.txt`

I also had a strange issue where the bot env file pointed to klipper's `printer.cfg`:

```
$ cat /home/klipper/printer_data/systemd/moonraker-telegram-bot.env
TELEGRAM_BOT_ARGS="/home/klipper/moonraker-telegram-bot/bot/main.py -c /home/klipper/printer_data/config/printer.cfg -l /home/klipper/printer_data/logs/telegram.log"
```
Manually updating this fixed the issue, but I'm not sure if that was an artifact of the most recent KIAUH install or not.

**Comment by dw-0** [comment]
Thank you for reporting this bug. I provided a fix and it will be released with v6.0.0-alpha.6
