### ISSUE TITLE
[Errno 18] Invalid cross-device link: '/tmp/tmpdrqggzl7' -> '/home/eggelen/printer_data/config/printer.cfg' during installation

### ISSUE THREAD

**Issue by EvEggelen** [dw-0/kiauh#563]
### Linux Distribution

Armbian_community_24.11.0-trunk.202_Orangepizero_bookworm_current_6.6.44_minimal

### What happened

-clean install of armbian on an orangepizero ( 512Mbyte)
-increase swap zram -> 1Gbyte
-install mdns ( sudo apt-get install avahi-daemon libnss-mdns libnss-mymachines )
-followed step 1 2 3 from ( https://github.com/dw-0/kiauh ) to run kiauh
-used alpha version
-installed klipper with default printer.cfg / 1 instance
-installed Moonraker (2)
-installed Mainsail (3)

During installation of mainsail I received an error in the log.  Not sure how severe the error is as it still seems to work
and the  "Add section '[update_manager mainsail-config]' to '/home/eggelen/printer_data/config/moonraker.conf'" is placed in the moonraker.conf

╔═══════════════════════════════════════════════════════╗
║ ~~~~~~~~~~~~~~~ [ Installation Menu ] ~~~~~~~~~~~~~~~ ║
╟───────────────────────────┬───────────────────────────╢
║ Firmware & API:           │ Touchscreen GUI:          ║
║  1) [Klipper]             │  7) [KlipperScreen]       ║
║  2) [Moonraker]           │                           ║
║                           │ Webcam Streamer:          ║
║ Webinterface:             │  8) [Crowsnest]           ║
║  3) [Mainsail]            │                           ║
║  4) [Fluidd]              │                           ║
║                           │                           ║
║ Client-Config:            │                           ║
║  5) [Mainsail-Config]     │                           ║
║  6) [Fluidd-Config]       │                           ║
╟───────────────────────────┴───────────────────────────╢
║                       B) « Back                       ║
╚═══════════════════════════════════════════════════════╝
###### Perform action: 3

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                       [ INFO ]                        ┃
┠───────────────────────────────────────────────────────┨
┃ It is recommended to use special macros in order to   ┃
┃ have Mainsail fully functional and working.           ┃
┃                                                       ┃
┃ The recommended macros for Mainsail can be seen here: ┃
┃ https://github.com/mainsail-crew/mainsail-config      ┃
┃                                                       ┃
┃ If you already use these macros skip this step.       ┃
┃ Otherwise you should consider to answer with 'Y' to   ┃
┃ download the recommended macros.                      ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
###### Installing dependencies ...
[INFO] The following packages need installation:
● nginx
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  nginx-common
Suggested packages:
  fcgiwrap nginx-doc ssl-cert
The following NEW packages will be installed:
  nginx nginx-common
0 upgraded, 2 newly installed, 0 to remove and 6 not upgraded.
Need to get 583 kB of archives.
After this operation, 1,226 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main armhf nginx-common all 1.22.1-9 [112 kB]
Get:2 http://deb.debian.org/debian bookworm/main armhf nginx armhf 1.22.1-9 [471 kB]
Fetched 583 kB in 0s (3,589 kB/s)
Preconfiguring packages ...
Selecting previously unselected package nginx-common.
(Reading database ... 38107 files and directories currently installed.)
Preparing to unpack .../nginx-common_1.22.1-9_all.deb ...
Unpacking nginx-common (1.22.1-9) ...
Selecting previously unselected package nginx.
Preparing to unpack .../nginx_1.22.1-9_armhf.deb ...
Unpacking nginx (1.22.1-9) ...
Setting up nginx-common (1.22.1-9) ...
Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service → /lib/systemd/system/nginx.service.
Setting up nginx (1.22.1-9) ...
Upgrading binary: nginx.
Processing triggers for man-db (2.11.2-2) ...
[OK] Packages successfully installed.

###### Downloading Mainsail from https://github.com/mainsail-crew/mainsail/releases/latest/download/mainsail.zip ...
Downloading: [####################]100.00% (2.43/2.43MB)
[OK] Download complete!

###### Extracting mainsail.zip ...
[OK] OK!

###### Add section '[update_manager mainsail]' to '/home/eggelen/printer_data/config/moonraker.conf' ...
[OK] OK!

###### Restart moonraker.service ...
[OK] OK!

###### Cloning repository from 'https://github.com/mainsail-crew/mainsail-config.git'
Cloning into '/home/eggelen/mainsail-config'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 89 (delta 51), reused 21 (delta 21), pack-reused 33 (from 1)
Receiving objects: 100% (89/89), 43.76 KiB | 1.09 MiB/s, done.
Resolving deltas: 100% (52/52), done.
[OK] Clone successful!

###### Creating backup of config-printer_data in /home/eggelen/kiauh-backups/printer-cfg-backups ...
[OK] Backup successful!

###### Add section '[update_manager mainsail-config]' to '/home/eggelen/printer_data/config/moonraker.conf' ...
[OK] OK!
**[ERROR] Mainsail-Config installation failed!
[Errno 18] Invalid cross-device link: '/tmp/tmpdrqggzl7' -> '/home/eggelen/printer_data/config/printer.cfg'**

###### Granting NGINX the required permissions ...
[OK] Permissions granted.
[OK] NGINX config for Mainsail successfully created.

###### Restart nginx ...
[OK] OK!

[OK] Mainsail installation complete!
Open Mainsail now on: http://192.168.1.223:80

### What did you expect to happen

Install without errors

### How to reproduce

-clean install of armbian on an orangepizero ( 512Mbyte)
-increase swap zram -> 1Gbyte
-install mdns ( sudo apt-get install avahi-daemon libnss-mdns libnss-mymachines )
-followed step 1 2 3 from ( https://github.com/dw-0/kiauh ) to run kiauh
```
sudo apt-get update && sudo apt-get install git -y
cd ~ && git clone https://github.com/dw-0/kiauh.git
./kiauh/kiauh.sh
```

-used alpha version
-installed klipper with default printer.cfg / 1 instance
-installed Moonraker (2)
-installed Mainsail (3)

### Additional information

Not sure how severe the error is. But created a bug report as feedback is requested

[KIAUH Klipper Installation.txt](https://github.com/user-attachments/files/17270316/KIAUH.Klipper.Installation.txt)

**Comment by dw-0** [comment]
This looks like the same issue as in #509 

I will close this issue in favor of tracking the issue in #509
Thank you for reporting though!
