### ISSUE TITLE
Encoding error latin-1 (Kiauh Alpha v6)

### ISSUE THREAD

**Issue by naruhaxor** [dw-0/kiauh#576]
### Linux Distribution

Linux tronxy 6.6.51+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux

### What happened

[ERROR] An unexpected error occured:
'latin-1' codec can't encode characters in position 0-56: ordinal not in range(256)
Traceback (most recent call last):
  File "/home/trash/kiauh/kiauh/core/menus/base_menu.py", line 184, in run
    self.display_menu()
  File "/home/trash/kiauh/kiauh/core/menus/base_menu.py", line 177, in display_menu
    print_header()
  File "/home/trash/kiauh/kiauh/core/menus/base_menu.py", line 50, in print_header
    print(header, end="")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-56: ordinal not in range(256)

### What did you expect to happen

the new python menu appearing

### How to reproduce

start KIAUH

select yes on trying out v6

### Additional information

this was on a rpi5 everything is up to date on the system

locale info

LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=en_US

**Comment by naruhaxor** [comment]
actually i found a way to fix this issues but it isnt persistent through reboots/updates


export PYTHONIOENCODING=utf-8

**Comment by dw-0** [comment]
Hi, thanks for the report.
Is it possible, that you have some non english special characters in one of your config files? During start, KIAUH scans through some files (mainly all moonraker.confs and KIAUHs own config) and i would assume something failed on that side.
Were there other errors or stacktraces as well? Or just the error message you provided?

**Comment by naruhaxor** [comment]
I've gone through my configs and nothing I don't use anything other then English as it's the only language I'm familiar with however I can try backing up my pi and doing a reflash to see if its still an issue

**Comment by dw-0** [comment]
I hoped to fix the issue with the patch i provided earlier. Does the issue still occurs even after updating KIAUH?

**Comment by naruhaxor** [comment]
I won't be able to check until I get home tonight however I will definitely
give it a shot

**Comment by naruhaxor** [comment]
i did a full reinstall of the OS and copied over all my info and YES it works now no issues ty patch works
