### ISSUE TITLE
interface error from installing spoolman

### ISSUE THREAD

**Issue by sastreae** [dw-0/kiauh#579]
### Linux Distribution

debian 11

### What happened

at the time of installing spoolman. A bad command line is added to the file /home/pi/printer_data/moonraker.asvc
. The word spoolman is not written on a new line but is written next to the last installation

### What did you expect to happen

It should be written one line below so that it is well read by the system

### How to reproduce

first installation of klipper, installing several more programs, when installing spoolman an error appears on the screen

### Additional information

When the error appears, it does not allow you to give screen commands. but continue accessing normally via ssh.

**Comment by dw-0** [comment]
Thanks for the report. I was able to reproduce the issue and will provide a fix soon.

**Comment by sastreae** [comment]
thanks to you.
